name: Compiling and testing CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: make check
      run: make test
    - name: Run the tool
      run: ./free
    - uses: actions/upload-artifact@v4
      name: Upload the binary
      with:
        name: free-0.1-${{ github.run_number }}
        path: ${{ github.workspace }}/publish/*
